config/routes.rb
Rails.application.routes.draw do

  get "/404" => "errors#not_found"
  get "/500" => "errors#internal_server_error"

  resources :issues do
    get :prepare_form, on: :member
    patch :prepare, on: :member
    patch :publish, on: :member
    get :reviews, on: :member
    get :statistics, on: :member
    get :reviewers, on: :member
    get :summary, on: :member
    get :table_of_contents, on: :member
  end
  resources :public_issues, only: [:index,:show] do
    get :reviewers, on: :member
  end
  resources :people do
    get :search, on: :member
  end
  resources :submissions do
    post :send_decision, on: :member
  end
  resources :public_submissions, only: [:new, :create] do
    post :add_author, on: :collection
    member do
      post :add_reviewer
      post :cancel
      post :finish
    end
  end
  resources :user_submissions, only: [:index, :show]
  resources :affiliations, only: [:new, :create, :destroy] do
    get :institutions, on: :collection
    get :countries, on: :collection
    get :departments, on: :collection
  end
  resources :authorships, only: [:new, :create, :destroy] do
    post :sign, on: :member
  end
  resources :reviews do
    member do
      post :ask
      post :send_status
      patch :ask_for_review
      get :ask_for_review_preview
      patch :send_form
      get :form_preview
      patch :accepted
      patch :rejected
    end
  end
  resources :public_reviews, only: [:edit, :update] do
    member do
      get :accepted_form
      patch :accepted
      get :rejected_form
      patch :rejected
    end
  end
  resources :article_revisions, only: [:new, :create, :destroy]
  resources :article_revisions
  resources :articles do
    get :generate_certificate, on: :member
  end
  resources :public_revisions, only: [:new, :create]
  resource :profile, only: [:show, :edit, :update] do
    get :edit_password
    patch :update_password
  end
  resources :public_articles, only: [:show]

  get 'mails/write_email/:id', to: 'mails#write_email', as: :write_email
  post 'mails/send_email', to: 'mails#send_email', as: :send_email

  resources :users, only: [:new, :create] do
    get :new_person, on: :collection
    post :create_person, on: :collection
  end
  devise_for :users
  mount Storytime::Engine => "/"
  root to: "blog_posts#index"
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  validates :year, presence: true, numericality: {greater_than: 2000}
  validates :volume, presence: true, numericality: {greater_than: 0}, uniqueness: true

  has_many :submissions
  has_many :articles

  scope :published, -> { where(published: true) }
  scope :latest, -> { order("volume desc") }

  def title
    "#{self.volume}\/#{self.year}"
  end

  def submissions_ready?
    !self.submissions.accepted.empty?
  end

  def publish
    self.update_attributes(published: true)
  end

  def prepare_to_publish(ids)
    begin
      self.transaction do
        ids.each do |id|
          submission = Submission.find_by_id(id)
          next unless submission
          Article.create!(submission: submission, issue: self, status: "po recenzji")
        end
        self.update_attributes(prepared: true)
      end
      true
    rescue
      false
    end
  end

  def status
    if self.published?
      "Opublikowany"
    elsif self.prepared?
      "Do publikacji"
    else
      ""
    end
  end

  def to_param
    [volume, year].join("-")
  end

  def authors_count(type,scope)
    self.author_division(scope)[type]
  end

  def total_authors_count(scope)
    authors_count(:polish, scope) + authors_count(:foreign, scope)
  end

  def authors_percentage(type, scope)
    percentage(self.author_division(scope)[type], self.total_authors_count(scope))
  end

  def submissions_count(type,scope)
    case scope
    when :all
      case type
      when :english
        self.submissions.english.count
      when :polish
        self.submissions.polish.count
      else
        raise "Invalid submission type '#{type}'"
      end
    when :accepted
      case type
      when :english
        self.articles.english.count
      when :polish
        self.articles.polish.count
      else
        raise "Invalid submission type '#{type}'"
      end
    else
      raise "Invalid submission scope '#{scope}'"
    end
  end

  def total_submissions_count(scope)
    submissions_count(:polish,scope) + submissions_count(:english,scope)
  end

  def submissions_percentage(type,scope)
    percentage(submissions_count(type,scope),total_submissions_count(scope))
  end

  def reviewers_count(type,scope)
    case type
    when :uj, :other
      institution_division(scope)[type]
    when :polish, :foreign
      reviewers_division(scope)[type]
    else
      raise "Invalid reviewer type '#{type}'"
    end
  end

  def reviewers_count_by_country(scope)
    reviewers_count(:polish,scope) + reviewers_count(:foreign,scope)
  end

  def reviewers_count_by_institution(scope)
    reviewers_count(:polish,scope) + reviewers_count(:foreign,scope)
  end

  def reviewers_percentage(type,scope)
    case type
    when :polish, :foreign
      percentage(reviewers_count(type,scope),reviewers_count_by_country(scope))
    when :uj, :other
      percentage(reviewers_count(type,scope),reviewers_count_by_institution(scope))
    else
      raise "Invalid reviewer type '#{type}'"
    end
  end

  def unique_reviewers(scope)
    collection =
      if scope == :all
        self.submissions
      else
        self.articles
      end
    collection.flat_map{|a| a.reviews.select(&:done?).flat_map{|r| r.person } }.uniq
  end

  protected
  def percentage(count,total)
    if total > 0
      (count  * 100 / total).round
    else
      0
    end
  end

  def institution_division(scope)
    return @institution_division[scope] if @institution_division && @institution_division[scope]
    @institution_division ||= {}
    @institution_division[scope] = Hash.new(0)
    self.unique_reviewers(scope).each do |reviewer|
      if reviewer.from_uj?
        @institution_division[scope][:uj] += 1
      else
        @institution_division[scope][:other] += 1
      end
    end
    @institution_division[scope]
  end

  def author_division(scope)
    return @author_division[scope] if @author_division && @author_division[scope]
    @author_division ||= {}
    @author_division[scope] = Hash.new(0)
    if scope == :all
      collection = self.submissions
    else
      collection = self.articles
    end
    authors = collection.flat_map{|i| i.authors }.uniq
    authors.each do |author|
      if author.polish?
        @author_division[scope][:polish] += 1
      else
        @author_division[scope][:foreign] += 1
      end
    end
    @author_division[scope]
  end

  def reviewers_division(scope)
    return @reviewer_division[scope] if @reviewer_division && @reviewer_division[scope]
    @reviewer_division ||= {}
    @reviewer_division[scope] = Hash.new(0)
    self.unique_reviewers(scope).each do |reviewer|
      if reviewer.polish?
        @reviewer_division[scope][:polish] += 1
      else
        @reviewer_division[scope][:foreign] += 1
      end
    end
    @reviewer_division[scope]
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :admin_required
  layout "admin"
  before_action -> {set_title "Numery rocznika"}

  def index
    @query_params = params[:q] || {}
    @query = Issue.ransack(@query_params)
    @query.sorts = ['year desc','volume desc'] if @query.sorts.empty?
    @issues = @query.result(distinct: true)
  end


  def publish
    @issue = find_issue
    @issue.publish
    redirect_to @issue
  end

  def new
    @issue = Issue.new
  end

  def prepare_form
    @issue = find_issue
  end

  def prepare
    @issue = Issue.find_by_volume(params[:id])
    if params[:issue][:submission_ids] && @issue.prepare_to_publish(params[:issue][:submission_ids])
      redirect_to @issue
    else
      render :prepare_form
    end
  end

  def create
    @issue = Issue.new(issue_params)
    if @issue.save
      redirect_to @issue
    else
      render :new
    end
  end

  def edit
    @issue = find_issue
  end

  def update
    @issue = Issue.find_by_volume(params[:id])
    if @issue.update_attributes(issue_params)
      redirect_to @issue
    else
      render :edit
    end
  end

  def show
    @issue = find_issue
  end

  def summary
    @issue = find_issue
  end


  def reviews
    @issue = find_issue
  end

  def statistics
    @issue = find_issue
  end

  def reviewers
    @issue = find_issue
  end

  def table_of_contents
    @issue = find_issue
  end

  private

  def issue_params
    params.require(:issue).permit(:year,:volume)
  end

  def find_issue
    Issue.find_by_volume(params[:id])
  end

end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.haml
= simple_form_for @issue do |f|
  = f.input :volume, label: "Numer"
  = f.input :year, label: "Rok"
  - label = @issue.new_record? ? "Utwórz" : "Zapisz"
  = f.submit label, class: %w{btn btn-primary btn-outline}

app/views/issues/edit.html.haml
.scroll-panel-header
  = link_to "Anuluj", @issue, class: %w{btn btn-default btn-sm pull-right}
  %h3.scroll-panel-title Edycja numeru
.scroll-panel-body
  = render partial: "form"

app/views/issues/index.html.haml
.scroll-panel-header
  = link_to "Nowy numer", new_issue_path, class: %w{btn btn-default btn-sm pull-right}
  %h3.scroll-panel-title Numery rocznika
.scroll-panel-body
  %table.table.table-hover.table-admin
    %thead
      %tr#stickedHeader.static
        %th Numer
        %th Rok
        %th Liczba zgłoszeń
        %th Liczba artykułów
        %th Status
    %tbody
      - @issues.each do |issue|
        %tr.table-row-link{"data-url" => issue_path(issue) }
          %td= link_to issue.volume, issue
          %td= issue.year
          %td= issue.submissions.count
          %td= issue.articles.count
          %td= issue.status

app/views/issues/js_position.html.haml
:javascript
  $(document).ready(function () {
    $('.fa-chevron-up').click(function () {
      if (check_prev_sibling_exist($(this))) {
        ajax_on_demand($(this), -1);        
      }
    });

    $('.fa-chevron-down').click(function () {
      if (check_next_sibling_exist($(this))) {
        ajax_on_demand($(this), 1);
      }
    });
  });

  function ajax_on_demand(item, direction) {
    $.ajax({
      method: 'PATCH',
      url: get_base_url() + "/articles/" + parseInt($(item).siblings('.article-id').text()),
      dataType: 'json',
      data: JSON.stringify({issue_position: parseInt($(item).siblings('.issue-position').text())+direction}),
      headers: {
          "Content-type":"application/json"
      },
      success: function(rails_response) {
        if (rails_response.ok) {
          update_queue($(item), direction);
        }
      },
      error: function() {
        return false;
      }
    });
  }

  function update_queue(item, direction) {
    update_position_values(item, direction);
    update_position_queue(item, direction);
  }

  function update_position_values(item, direction) {
    var clicked_article = $(item).siblings('.issue-position');
    var clicked_art_value = clicked_article.text();
    var sibling = get_row_sibling(item, direction)

    if (sibling) {
      var other_article = $(sibling).children().children('.issue-position');
      clicked_article.text(other_article.text());
      other_article.text(clicked_art_value);
    }
  }

  function update_position_queue(item, direction) {
    var article = get_row(item);
    var sibling = get_row_sibling(item, direction)
    direction >= 1 ? $(sibling).after(article) : $(sibling).before(article);
  }

  function get_row_sibling(item, direction) {
    if (direction >= 1) {
      return get_row(item).next();
    }
    return get_row(item).prev();
  }

  function get_row(item) {
    return $(item).parent().parent();
  }

  function check_prev_sibling_exist(item) {
    return get_row(item).prev().is("tr") ? true : false;
  }

  function check_next_sibling_exist(item) {
    return get_row(item).next().is("tr") ? true : false;
  }

  function get_base_url() {
    return location.origin;
  }

app/views/issues/new.html.haml
.scroll-panel-header
  = link_to "Anuluj", issues_path, class: %w{btn btn-default btn-sm pull-right}
  %h3.scroll-panel-title Nowy numer
.scroll-panel-body
  = render partial: "form"

app/views/issues/prepare_form.html.haml
.scroll-panel-header
  = link_to "Anuluj", @issue, class: %w{btn btn-default btn-sm pull-right}
  %h3.scroll-panel-title Przygotuj numer do wydania
.scroll-panel-body
  = simple_form_for @issue, :url => prepare_issue_path(@issue) do |f|
    = f.association :submissions, label: "Wybierz artykuły do wydania w tym numerze", collection: @issue.submissions.accepted, include_blank: false, label_method: :title, :as => :check_boxes
    = f.submit "Przygotuj numer do wydania", class: %w{btn btn-primary btn-outline}

app/views/issues/published.html.haml
.scroll-panel-header
  %h3.scroll-panel-title Numery rocznika
.scroll-panel-body
  %table.table.table-hover.table-admin
    %thead
      %tr
        %th Numer
        %th Rok
        %th Liczba artykułów
    %tbody
      - @issues.each do |issue|
        %tr.table-row-link{"data-url" => issue_path(issue) }
          %td= link_to issue.volume, issue
          %td= issue.year
          %td= issue.articles.count

app/views/issues/reviewers.html.haml
.scroll-panel-header
  = link_to "Wróć do numeru", issue_path, class: %w{btn btn-default btn-sm pull-right}
  %h3.scroll-panel-title
    Recenzenci numeru
    = @issue.title
.scroll-panel-body
  - @issue.unique_reviewers(:all).sort_by{|r| r.surname }.each do |reviewer|
    .scroll-panel_body
      Recenzent:
      = link_to reviewer.full_name, reviewer
      %br

app/views/issues/reviews.html.haml
.scroll-panel-header
  = link_to "Wróć do numeru", issue_path, class: %w{btn btn-default btn-sm pull-right}
  %h3.scroll-panel-title
    Recenzje zgłoszeń do numeru
    = @issue.title
.scroll-panel-body
  - @issue.articles.order(:issue_position).each do |article|
    %h2= link_to article.title, article.submission
    %i= article.authors_inline
    .scroll-panel_body
      - article.reviews.select(&:done?).group_by(&:person).each do |reviewer,reviews|
        %h3
          Recenzent:
          = reviewer.full_name
        - reviews.each do |review|
          %h4
            Wersja
            = review.version
          = simple_format(review.text)

app/views/issues/show.html.haml
= render file: "issues/js_position"
.scroll-panel-header
  -unless @issue.published?
    - if @issue.prepared?
      = link_to "Wydaj numer", publish_issue_path(@issue), class: %w{btn btn-default btn-sm pull-right}, method: :patch
    - else
      = link_to "Przygotuj do wydania", prepare_form_issue_path(@issue), class: ['btn btn-default btn-sm pull-right', ('disabled' unless @issue.submissions_ready?)]
  = link_to "Numery rocznika", issues_path, class: %w{btn btn-default btn-sm pull-right}
  = link_to "Nowy numer", new_issue_path, class: %w{btn btn-default btn-sm pull-right}
  %h3.scroll-panel-title
    Numer
    = @issue.title
    = @issue.published? ? " [OPUBLIKOWANY]" : ""
  = link_to "Edytuj", edit_issue_path(@issue), class: %w{btn btn-primary btn-sm}
  = link_to "Pokaż recenzje", reviews_issue_path(@issue), class: %w{btn btn-default btn-sm}
  = link_to "Statystyki", statistics_issue_path(@issue), class: %w{btn btn-default btn-sm}
  = link_to "Pokaż recenzentów", reviewers_issue_path(@issue), class: %w{btn btn-default btn-sm}
  = link_to "Podsumowanie", summary_issue_path(@issue), class: %w{btn btn-default btn-sm}
  = link_to "Spis treści", table_of_contents_issue_path(@issue), class: %w{btn btn-default btn-sm}
.scroll-panel-body
  -if @issue.prepared?
    %h3 Publikowane artykuły
    %table.table.table-hover.table-admin
      %thead
        %tr
          %th Kolejność
          %th Tytuł
          %th Autorzy
          %th Status
      %tbody
        - @issue.articles.order(:issue_position).each do |article|
          %tr
            %td
              %i{class: "fa fa-chevron-up btn", id: "article-up"}
              %i{class: "fa fa-chevron-down btn", id: "article-down"}
            %td= link_to article.title, article.submission
            %td= article.authors_inline
            %td= article.status
  %h3 Zgłoszone artykuły
  %table.table.table-hover.table-admin
    %thead
      %tr
        %th Tytuł
        %th Data nadesłania
        %th Status
    %tbody
      - @issue.submissions.each do |submission|
        %tr
          %td= link_to submission.title, submission
          %td= submission.received.strftime("%d-%m-%Y")
          %td{class: "#{Submission::STATUS_MAPPING[submission.status]}"}= submission.status
          %td.text-right
            = destroy_button(submission, "Czy na pewno chcesz usunąć to zgłoszenie?")

app/views/issues/show_published.html.haml
.scroll-panel-header
  %h3.scroll-panel-title
    Numer
    = @issue.title
.scroll-panel-body
  %h3 Artykuły
  %ul
    - @issue.articles.each do |article|
      %li= article.authorsAndTitle

app/views/issues/statistics.html.haml
.scroll-panel-header
  = link_to "Wróć do numeru", issue_path, class: %w{btn btn-default btn-sm pull-right}
  %h2.scroll-panel-title
    Statystyki do numeru
    = @issue.title
.scroll-panel-body
  %h3 Statystki artykułów zgłoszonych
  %table.table.table-hover.table-admin
    %thead
      %tr
        %th Parametr
        %th Liczba
        %th W sumie
        %th Udział procentowy %
    %tbody
      %tr
        %td Liczba artykułów w j. polskim
        %td= @issue.submissions_count(:polish,:all)
        %td= @issue.total_submissions_count(:all)
        %td= @issue.submissions_percentage(:polish,:all)
      %tr
        %td Liczba artykułów w j. angielskim
        %td= @issue.submissions_count(:english,:all)
        %td= @issue.total_submissions_count(:all)
        %td= @issue.submissions_percentage(:english,:all)
      %tr
        %td Liczba autorów z afiliacją polską
        %td= @issue.authors_count(:polish,:all)
        %td= @issue.total_authors_count(:all)
        %td= @issue.authors_percentage(:polish,:all)
      %tr
        %td Liczba autorów z afiliacją zagraniczną
        %td= @issue.authors_count(:foreign,:all)
        %td= @issue.total_authors_count(:all)
        %td= @issue.authors_percentage(:foreign,:all)
      %tr
        %td Liczba recenzentów z Uniwersytetu Jagiellońskiego
        %td= @issue.reviewers_count(:uj,:all)
        %td= @issue.reviewers_count_by_institution(:all)
        %td= @issue.reviewers_percentage(:uj,:all)
      %tr
        %td Liczba recenzentów z innych uczelni
        %td= @issue.reviewers_count(:other,:all)
        %td= @issue.reviewers_count_by_institution(:all)
        %td= @issue.reviewers_percentage(:other,:all)
      %tr
        %td Liczba recenzentów z Polski
        %td= @issue.reviewers_count(:polish,:all)
        %td= @issue.reviewers_count_by_country(:all)
        %td= @issue.reviewers_percentage(:polish,:all)
      %tr
        %td Liczba recenzentów spoza Polski
        %td= @issue.reviewers_count(:foreign,:all)
        %td= @issue.reviewers_count_by_country(:all)
        %td= @issue.reviewers_percentage(:foreign,:all)
  -if @issue.prepared?
    %h3 Statystki artykułów przyjętych do druku
    %table.table.table-hover.table-admin
      %thead
        %tr
          %th Parametr
          %th Liczba
          %th W sumie
          %th Udział procentowy %
      %tbody
        %tr
          %td Liczba artykułów w j. polskim
          %td= @issue.submissions_count(:polish,:accepted)
          %td= @issue.total_submissions_count(:accepted)
          %td= @issue.submissions_percentage(:polish,:accepted)
        %tr
          %td Liczba artykułów w j. angielskim
          %td= @issue.submissions_count(:english,:accepted)
          %td= @issue.total_submissions_count(:accepted)
          %td= @issue.submissions_percentage(:english,:accepted)
        %tr
          %td Liczba autorów z afiliacją polską
          %td= @issue.authors_count(:polish,:accepted)
          %td= @issue.total_authors_count(:accepted)
          %td= @issue.authors_percentage(:polish,:accepted)
        %tr
          %td Liczba autorów z afiliacją zagraniczną
          %td= @issue.authors_count(:foreign,:accepted)
          %td= @issue.total_authors_count(:accepted)
          %td= @issue.authors_percentage(:foreign,:accepted)
        %tr
          %td Liczba recenzentów z Uniwersytetu Jagiellońskiego
          %td= @issue.reviewers_count(:uj,:accepted)
          %td= @issue.reviewers_count_by_institution(:accepted)
          %td= @issue.reviewers_percentage(:uj,:accepted)
        %tr
          %td Liczba recenzentów z innych uczelni
          %td= @issue.reviewers_count(:other,:accepted)
          %td= @issue.reviewers_count_by_institution(:accepted)
          %td= @issue.reviewers_percentage(:other,:accepted)
        %tr
          %td Liczba recenzentów z Polski
          %td= @issue.reviewers_count(:polish,:accepted)
          %td= @issue.reviewers_count_by_country(:accepted)
          %td= @issue.reviewers_percentage(:polish,:accepted)
        %tr
          %td Liczba recenzentów spoza Polski
          %td= @issue.reviewers_count(:foreign,:accepted)
          %td= @issue.reviewers_count_by_country(:accepted)
          %td= @issue.reviewers_percentage(:foreign,:accepted)

app/views/issues/summary.html.haml
.scroll-panel-header
  = link_to "Wróć do numeru", issue_path, class: %w{btn btn-default btn-sm pull-right}
  %h3.scroll-panel-title
    Podsumowanie numeru
    = @issue.title
.scroll-panel-body
  - @issue.articles.order(:issue_position).each do |article|
    .scroll-panel_body
      %h4
        = "#{article.issue_position}. #{article.title}"
        - if article.polish_language?
          %br
          = "(ang.) #{article.english_title}"
      %p
        %strong Autorzy
        - article.authors.each.with_index do |author,index|
          - if index > 0
            ,
          - if author == article.corresponding_author
            = link_to author.full_name, "mailto:#{author.email}"
          - else
            = author.full_name
      %p
        %strong Streszczenie
      %p= article.abstract
      %p
        %strong Słowa kluczowe
      %p= article.keywords

app/views/issues/table_of_contents.html.haml
.scroll-panel-header
  = link_to "Wróć do numeru", issue_path, class: %w{btn btn-default btn-sm pull-right}
.scroll-panel-body
  %h3
    Spis treści
    = @issue.title
  - @issue.articles.order(:issue_position).each do |article|
    .scroll-panel_body
      %h4
        = "#{article.issue_position}. "
        - if article.polish_title.blank?
          [BRAK POLSKIEGO TYTUŁU]
        - else
          = article.polish_title
      %p= article.authors_inline
  %h3
    Table of contents
    = @issue.title
  - @issue.articles.order(:issue_position).each do |article|
    .scroll-panel_body
      %h4
        = "#{article.issue_position}. "
        - if article.english_title.blank?
          [BRAK ANGIELSKIEGO TYTUŁU]
        - else
          = article.english_title
      %p= article.authors_inline