config/routes.rb
Rails.application.routes.draw do

  get "/404" => "errors#not_found"
  get "/500" => "errors#internal_server_error"

  resources :issues do
    get :prepare_form, on: :member
    patch :prepare, on: :member
    patch :publish, on: :member
    get :reviews, on: :member
    get :statistics, on: :member
    get :reviewers, on: :member
    get :summary, on: :member
    get :table_of_contents, on: :member
  end
  resources :public_issues, only: [:index,:show] do
    get :reviewers, on: :member
  end
  resources :people do
    get :search, on: :member
  end
  resources :submissions do
    post :send_decision, on: :member
  end
  resources :public_submissions, only: [:new, :create] do
    post :add_author, on: :collection
    member do
      post :add_reviewer
      post :cancel
      post :finish
    end
  end
  resources :user_submissions, only: [:index, :show]
  resources :affiliations, only: [:new, :create, :destroy] do
    get :institutions, on: :collection
    get :countries, on: :collection
    get :departments, on: :collection
  end
  resources :authorships, only: [:new, :create, :destroy] do
    post :sign, on: :member
  end
  resources :reviews do
    member do
      post :ask
      post :send_status
      patch :ask_for_review
      get :ask_for_review_preview
      patch :send_form
      get :form_preview
      patch :accepted
      patch :rejected
    end
  end
  resources :public_reviews, only: [:edit, :update] do
    member do
      get :accepted_form
      patch :accepted
      get :rejected_form
      patch :rejected
    end
  end
  resources :article_revisions, only: [:new, :create, :destroy]
  resources :article_revisions
  resources :articles do
    get :generate_certificate, on: :member
  end
  resources :public_revisions, only: [:new, :create]
  resource :profile, only: [:show, :edit, :update] do
    get :edit_password
    patch :update_password
  end
  resources :public_articles, only: [:show]

  get 'mails/write_email/:id', to: 'mails#write_email', as: :write_email
  post 'mails/send_email', to: 'mails#send_email', as: :send_email

  resources :users, only: [:new, :create] do
    get :new_person, on: :collection
    post :create_person, on: :collection
  end
  devise_for :users
  mount Storytime::Engine => "/"
  root to: "blog_posts#index"
end

app/views/shared/adminnav.html.haml
%li= link_to "Numery rocznika", issues_path
%li= link_to "Osoby", people_path
%li= link_to "Zgłoszone artykuły", submissions_path
%li= link_to "Publikowane artykuły", articles_path
%li= link_to "Recenzje", reviews_path
%li= link_to "Edycja", "storytime"

app/views/shared/flash.html.haml
- if flash[:error]
  .alert.alert-danger.alert-dismissible
    %button{:type => "button", :class => "close", "data-dismiss" => "alert", "aria-label" => "Close"}
      %span{"aria-hidden" => "true"}
        &times;
    = flash[:error]
- if flash[:notice]
  .alert.alert-success.alert-dismissible
    %button{:type => "button", :class => "close", "data-dismiss" => "alert", "aria-label" => "Close"}
      %span{"aria-hidden" => "true"}
        &times;
    = flash[:notice]

app/views/shared/footer.html.haml
.container
  %ul.nav.navbar-nav.navbar-right
    %li
      %a{:href => "http://www.apohllo.pl", :target => "_blank"}
        Administrator

app/views/shared/head.html.haml
%head
  - if request.url.include? "/public_articles/"
    %meta{:name => "citation_title", :content => @article.title}
    - @article.authors_metadata.each do |author|
      %meta{:name => "citation_author", :content => author}
    %meta{:name => "citation_publication_date", :content => @article.year}
    %meta{:name => "citation_journal_title", :content => "Rocznik Kognitywistyczny"}
    %meta{:name => "citation_issue", :content => @article.issue_title}
  %title= @site_title
  %meta{:content => "http://rocznik.kognitywistyka.eu/", :property => "og:url"}/
  %meta{:content => "website", :property => "og:type"}/
  %meta{:content => "Rocznik Kognitywistyczny", :property => "og:title"}/
  %meta{:content => "Rocznik Kognitywistyczny", :property => "og:site_name"}/
  %meta{:content => "pl_PL", :property => "og:locale"}/
  %meta{:content => "https://scontent.xx.fbcdn.net/hphotos-xpf1/v/t1.0-9/993579_214000795601414_6530515180633938649_n.png?oh=0e1206aa6bbe51a6a0140437aaf1d5b5&oe=571504F7", :property => "og:image"}/
  %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
  %meta{"http-equiv" => "X-UA-Compatible", "content" => "IE=edge"}
  %meta{:charset => "utf-8"}/
  %meta{"name" => "viewport", "content" => "width=device-width, initial-scale=1"}
  %meta{:content => "Aleksander Smywiński-Pohl, Marta Siedlecka, Adrianna Smurzyńska", :name => "author"}/
  %meta{:content => "Rocznik Kognitywistyczny -- czasopismo naukowe, 5 punktów MNiSW", :name => "description"}/
  %meta{:content => "kognitywistyka, sztuczna inteligencja, lingwistyka, psychologia, informatyka, filozofia, koło naukowe, konferencja naukowa", :name => "keywords"}/
  %link{:href => "https://fonts.googleapis.com/css?family=Montserrat:400,700", :rel => "stylesheet", :type => "text/css"}/
  %link{:href => "https://fonts.googleapis.com/css?family=Kaushan+Script", :rel => "stylesheet", :type => "text/css"}/
  %link{:href => "https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic", :rel => "stylesheet", :type => "text/css"}/
  %link{:href => "https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700", :rel => "stylesheet", :type => "text/css"}/
  %meta{:content => "index, follow", :name => "robots"}/
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = stylesheet_link_tag    'storytime/application', media: 'all'
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = javascript_include_tag '//cdn.jsdelivr.net/webshim/1.14.5/polyfiller.js'
  = csrf_meta_tags
  /[if lt IE 9]
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>

app/views/shared/head_new.html.haml
%head
  /[if lt IE 9]
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>

app/views/shared/js_footer.html.haml
:javascript
  $(document).ready(function() {
    !function(d,s,id){
        var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';
        if(!d.getElementById(id)){
            js=d.createElement(s);
            js.id=id;
            js.src=p+'://platform.twitter.com/widgets.js';
            fjs.parentNode.insertBefore(js,fjs);
        }
    }(document, 'script', 'twitter-wjs');
  });
  $(document).ready(function() {
    (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/pl_PL/sdk.js#xfbml=1&version=v2.5";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
  });
  $(document).ready(function() {
    /*$('.flash').fadeOut(2000,function(el){ el.hide(); })*/
  });
  $(document).ready(function() {
      var showChar = 100; // How many characters are shown by default
      var ellipsestext = "...";
      var moretext = "<div class='btn btn-default btn-sm'>Rozwiń &raquo;</div>";
      var lesstext = "<div class='btn btn-default btn-sm'> &laquo; Zwiń</div>";


      $('.more').each(function() {
          var content = $(this).html();

          if(content.length > showChar) {

              var c = content.substr(0, showChar);
              var h = content.substr(showChar, content.length - showChar);

              var html = c + '<span class="moreellipses">' + ellipsestext+ '&nbsp;</span><span class="morecontent"><span>' + h + '</span>&nbsp;&nbsp;<a href="" class="morelink">' + moretext + '</a></span>';

              $(this).html(html);
          }
      });

      $(".morelink").click(function(){
          if($(this).hasClass("less")) {
              $(this).removeClass("less");
              $(this).html(moretext);
          } else {
              $(this).addClass("less");
              $(this).html(lesstext);
          }
          $(this).parent().prev().toggle();
          $(this).prev().toggle();
          return false;
      });
  });
  webshims.setOptions('forms-ext', {types: 'date'});
  webshims.polyfill('forms forms-ext');
  $(document).ready(function() {
  });

app/views/shared/sidenav.html.haml
%ul.nav.navbar-sidebar.nav-pills.nav-stacked
  %li{:class => active?("")}
    = link_to "Strona główna", "/"
  %li{:class => active?("cfp-kognitywistyka-krytyki-i-kontrowersje")}
    = link_to "Temat specjalny", "/cfp-kognitywistyka-krytyki-i-kontrowersje"
  %li{:class => active?("redakcja")}
    = link_to "Redakcja", "/redakcja"
  %li{:class => active?("procedura-recenzyjna")}
    = link_to "Procedura recenzyjna", "/procedura-recenzyjna"
  %li{:class => active?("wytyczne-dla-autorow")}
    = link_to "Wytyczne dla autorów", "/wytyczne-dla-autorow"
  %li{:class => [active?("public_submissions/new"), "call-to-action"]}= link_to "Zgłoś artykuł", new_public_submission_path
  - if user?
    %li{:class => active?("profile")}= link_to "Twój profil", profile_path
    %li{:class => active?("user_submissions")}= link_to "Twoje artykuły", user_submissions_path
  %li{:class => active?(public_issues_path)}= link_to "Numery", public_issues_path
  - Issue.published.sort_by{|i| - i.volume }.each do |issue|
    %li{:class => active?(public_issue_path(issue))}= link_to issue.title, public_issue_path(issue)
.sm-buttons.icon-bar.vertical
  .fb-like{"data-action" => "like", "data-href" => "https://www.facebook.com/Rocznik-Kognitywistyczny-213997978935029/", "data-layout" => "button", "data-share" => "true", "data-show-faces" => "true", "data-width" => "300"}
  .twitter-like
    %a.twitter-follow-button{"data-show-count" => "false", "data-size" => "small", :href => "https://twitter.com/RocznikKog"} Follow @RocznikKog

app/views/shared/topnav.html.haml
.container
  .navbar-header
    %button.navbar-toggle{ :type => "button", "data-toggle" => "collapse", "data-target" => ".navbar-collapse" }
      %span.sr-only Przełącz nawigację
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand{:href => root_url} Rocznik Kognitywistyczny
  .navbar-collapse.collapse
    %ul.nav.navbar-nav.navbar-right
      %li &nbsp;
      - if user?
        %li= link_to "Wyloguj", destroy_user_session_path, method: :delete
      - else
        %li= link_to "Zaloguj", new_user_session_path
      - if admin?
        = render file: "shared/adminnav"