config/routes.rb
Rails.application.routes.draw do

  get "/404" => "errors#not_found"
  get "/500" => "errors#internal_server_error"

  resources :issues do
    get :prepare_form, on: :member
    patch :prepare, on: :member
    patch :publish, on: :member
    get :reviews, on: :member
    get :statistics, on: :member
    get :reviewers, on: :member
    get :summary, on: :member
    get :table_of_contents, on: :member
  end
  resources :public_issues, only: [:index,:show] do
    get :reviewers, on: :member
  end
  resources :people do
    get :search, on: :member
  end
  resources :submissions do
    post :send_decision, on: :member
  end
  resources :public_submissions, only: [:new, :create] do
    post :add_author, on: :collection
    member do
      post :add_reviewer
      post :cancel
      post :finish
    end
  end
  resources :user_submissions, only: [:index, :show]
  resources :affiliations, only: [:new, :create, :destroy] do
    get :institutions, on: :collection
    get :countries, on: :collection
    get :departments, on: :collection
  end
  resources :authorships, only: [:new, :create, :destroy] do
    post :sign, on: :member
  end
  resources :reviews do
    member do
      post :ask
      post :send_status
      patch :ask_for_review
      get :ask_for_review_preview
      patch :send_form
      get :form_preview
      patch :accepted
      patch :rejected
    end
  end
  resources :public_reviews, only: [:edit, :update] do
    member do
      get :accepted_form
      patch :accepted
      get :rejected_form
      patch :rejected
    end
  end
  resources :article_revisions, only: [:new, :create, :destroy]
  resources :article_revisions
  resources :articles do
    get :generate_certificate, on: :member
  end
  resources :public_revisions, only: [:new, :create]
  resource :profile, only: [:show, :edit, :update] do
    get :edit_password
    patch :update_password
  end
  resources :public_articles, only: [:show]

  get 'mails/write_email/:id', to: 'mails#write_email', as: :write_email
  post 'mails/send_email', to: 'mails#send_email', as: :send_email

  resources :users, only: [:new, :create] do
    get :new_person, on: :collection
    post :create_person, on: :collection
  end
  devise_for :users
  mount Storytime::Engine => "/"
  root to: "blog_posts#index"
end

app/controllers/public_submissions_controller.rb
# encoding: utf-8

class PublicSubmissionsController < ApplicationController
  before_action -> {set_title "Nowe zgłoszenie"}
  before_action :check_submission, except: [:new, :create]

  def new
    @submission = Submission.new
    @submission.article_revisions.build(version: 1)
    @step = :new
  end

  def create
    @submission = Submission.new(submission_params)
    @submission.status = 'nadesłany'
    @submission.received = DateTime.current
    @submission.article_revisions.first.received = @submission.received

    if @submission.save
      build_authorship
      @step = :authors
      render :add_author
    else
      @step = :new
      render :new
    end
  end


  def add_author
    @authorship = Authorship.new(authorship_params)
    @submission = @authorship.submission
    @authorship.person = Person.find_by(email: @authorship.email) || @authorship.person
    @step = :authors
    if @authorship.save
      build_authorship(position: @authorship.position + 1, corresponding: false)
      flash[:notice] = 'Autor został dodany pomyślnie'
    else
      flash[:error] = 'Wystąpił błąd'
    end
  end

  def add_reviewer
    @submission = Submission.find(params[:id])
    @step = :reviewers
    unless params[:review]
      @review = build_review
      return
    end
    @review = Review.new(review_params)
    @review.person = Person.find_by(email: @review.email) || @review.person
    if @review.save
      @review = build_review
      flash[:notice] = 'Recenzent został dodany pomyślnie'
    else
      flash[:error] = 'Wystąpił błąd: ' + @review.errors.full_messages.join(", ")
    end
  end

  def finish
    @submission = Submission.find(params[:id])
    @step = :finish
    unless Person.editors.count.zero?
      EditorMailer.submission_notification(@submission).deliver_later
    end
    AuthorMailer.confirmation(@submission).deliver_later
  end

  def cancel
    @submission = Submission.find(params[:id])
    @submission.reviews.each{|r| r.destroy }
    @submission.article_revisions.each{|r| r.reload; r.destroy }
    @submission.reload
    @submission.destroy
    puts @submission.errors.full_messages
  end

  private
  def submission_params
    params.require(:submission).
      permit(:author_id, :english_abstract, :english_keywords, :english_title,
             :funding, :language, :polish_title,
             article_revisions_attributes: [ :pages, :pictures, :article ])
  end

  def build_authorship(attrs = {})
    attrs.reverse_merge!(position: 1, person: Person.new)
    @authorship = @submission.authorships.build(attrs)
  end

  def build_review
    review = Review.new
    review.person = Person.new
    review.article_revision = @submission.last_revision
    review
  end

  def authorship_params
    params.require(:authorship).
      permit(:corresponding, :position, :submission_id,
      person_attributes: [:name, :surname, :email, :sex])
  end

  def review_params
    params.require(:review).
      permit(:article_revision_id, :status, :remarks, person_attributes: [:name, :surname, :email, :sex])
  end

  def check_submission
    submission = Submission.find_by_id(params[:id])
    if submission && !submission.fresh?
      flash['error'] = 'Zgłoszenie jest już przetwarzane. Nie można go zmienić.'
      redirect_to root_path
    end
  end

end

app/views/public_submissions/_author_form.html.haml
%h4 Dodaj autora
= simple_form_for @authorship, url: add_author_public_submissions_path do |f|
  = f.input :submission_id, as: :hidden
  = f.input :position, as: :hidden
  = f.input :corresponding, label: "Korespondujący?", as: :boolean,
    item_wrapper_class: 'checkbox_container', hint: "Autor korespondujący jest odpowiedzialny za kontakt z redakcją Rocznika."
  = f.fields_for :person do |af|
    = af.input :name, label: "Imię"
    = af.input :surname, label: "Nazwisko"
    = af.input :email, label: "E-mail"
    = af.input :sex, collection: Person::SEX_MAPPING.keys, label: "Płeć"
  = f.submit "Dodaj autora", class: %w{btn btn-primary}
  - if @submission.authorships.count > 0
    = link_to "Dalej", add_reviewer_public_submission_path(@submission), class: %w{btn btn-outline btn-default},
      method: :post, data: {confirm: "Czy wszyscy autorzy zostali dodani?"}, title: "Przejdź do przedstawienia propozycji recenzentów"
  - else
    = link_to "Dalej", "#", class: %{btn disabled btn-default}, title: "Musisz dodać co najmniej jednego autora"
  = link_to "Rezygnuj", cancel_public_submission_path(@submission),  data: { confirm: "Czy chcesz wycofać zgłoszony artykuł?" },
    class: %w{btn btn-danger pull-right}, method: :post

app/views/public_submissions/_authors.html.haml
%table.table.table-hover.table-admin
  %thead
    %tr
      %th Imię i Nazwisko
      %th Email
      %th Korespondujący?
      %th Liczba porządkowa
  %tbody
    - @submission.authorships.each do |authorship|
      - unless authorship.new_record?
        %tr
          %td= authorship.author
          %td= authorship.email
          %td= authorship.corresponding? ? raw("&#10004;") : ""
          %td= authorship.position

app/views/public_submissions/_form.html.haml
= simple_form_for @submission, url: public_submissions_path do |f|
  = f.input :language, label: "Język", collection: %w{polski angielski}, include_blank: false
  = f.input :polish_title, label: "Tytuł polski",
    hint: "Polski tytuł artykułu, jeśli artykuł jest w języku polskim."
  = f.input :english_title, label: "Tytuł angielski", hint: "Angielski tytuł artykułu."
  = f.input :english_abstract, label: "Streszczenie", hint: "Angielskie streszczenie artykułu - niezależnie od języka artykułu."
  = f.input :english_keywords, label: "Słowa kluczowe", hint: "Angielskie słowa kluczowe - niezależnie od języka artykułu."
  = f.input :funding, label: "Finansowanie", hint: "Sekcja 'Finansowanie' jest przeznaczona do umieszczenia informacji, kto finansował badania opublikowane w artykule. Może być istotna w przypadku finansowania badań ze środków publicznych. Informacja ta zostanie umieszczona w artykule."
  = f.fields_for :article_revisions do |arf|
    = arf.input :pages, label: "Liczba stron", hint: "Liczba stron w dokumencie PDF - pomocna na etapie publikacji artykułu. Zalecana liczba stron: 10 - 20"
    = arf.input :pictures, label: "Liczba ilustracji", hint: "Liczba ilustracji w dokumencie PDF - pomocna na etapie publikacji artykułu"
    = arf.input :article, label: "Artykuł", hint: "Dokument w formacie PDF pozbawiony informacji o autorach artykułu."
  - label = "Dalej"
  = f.submit label, class: %w{btn btn-primary}
  = link_to "Anuluj", root_path, class: %w{btn btn-danger pull-right}

app/views/public_submissions/_reviewer_form.html.haml
%h4 Dodaj recenzenta
= simple_form_for @review, url: add_reviewer_public_submission_path(@submission) do |f|
  = f.input :article_revision_id, as: :hidden
  = f.input :status, collection: ["proponowany recenzent", "niechciany recenzent"], label: "Rodzaj propozycji",
    hint: "Twoje propozycje zostaną wzięte pod uwagę, lecz nie gwarantujemy tego, że z nich skorzystamy. W przypadku propozycji negatywnej wymagamy jej uzasadnienia."
  = f.input :remarks, label: "Uzasadnienie", as: :text
  = f.fields_for :person do |af|
    = af.input :name, label: "Imię"
    = af.input :surname, label: "Nazwisko"
    = af.input :email, label: "E-mail"
    = af.input :sex, collection: Person::SEX_MAPPING.keys, label: "Płeć"
  = f.submit "Dodaj recenzenta", class: %w{btn btn-primary}
  = link_to "Dalej", finish_public_submission_path(@submission), class: %w{btn btn-outline btn-default},
    method: :post, data: {confirm: "Czy wszystkie propozycje zostały dodane?"}, title: "Zakończ proces zgłaszania artykułu"
  = link_to "Rezygnuj", cancel_public_submission_path(@submission),  data: { confirm: "Czy chcesz wycofać zgłoszony artykuł?" },
    class: %w{btn btn-danger pull-right}, method: :post

app/views/public_submissions/_reviewers.html.haml
%table.table.table-hover.table-admin
  %thead
    %tr
      %th Imię i Nazwisko
      %th Email
      %th Rodzaj propozycji
      %th
  %tbody
    - @submission.reviews.each do |review|
      - unless review.new_record?
        %tr
          %td= review.reviewer
          %td= review.email
          %td= review.status

app/views/public_submissions/_timeline.html.haml
.timeline
  %div{class: (@step == :new ? 'active-entry' : 'entry')}
    Artykuł
  %div{class: (@step == :authors ? 'active-entry' : 'entry')}
    Autorzy
  %div{class: (@step == :reviewers ? 'active-entry' : 'entry')}
    Recenzenci
  %div{class: (@step == :finish ? 'last-active-entry' : 'last-entry')}
    Podsumowanie

app/views/public_submissions/add_author.html.haml
= render partial: "timeline"
.scroll-panel-body
  - if @submission.authorships.count > 0 # empty? doesn't worke since we have a fresh authorship
    = render partial: "authors"
  = render partial: "author_form"

app/views/public_submissions/add_reviewer.html.haml
= render partial: "timeline"
.scroll-panel-body
  - if @submission.reviews.count > 0 # empty? doesn't worke since we have a fresh authorship
    = render partial: "reviewers"
  = render partial: "reviewer_form"

app/views/public_submissions/cancel.html.haml
.scroll-panel-header
  %h3.scroll-panel-title Anulowano
.scroll-panel-body
  %h4 Twoje zgłoszenie zostało usunięte

app/views/public_submissions/finish.html.haml
= render partial: "timeline"
.scroll-panel-body
  %dl.dl-horizontal
    %dt Tytuł
    %dd= @submission.title
    %dt Język
    %dd= @submission.language
    %dt Otrzymano
    %dd= @submission.received.strftime("%d-%m-%Y")
    %dt Streszczenie
    %dd= @submission.abstract
    %dt Słowa kluczowe
    %dd= @submission.keywords
    - unless @submission.funding.blank?
      %dt Finansowanie
      %dd= simple_format(@submission.funding)
    %dt Autorzy
    %dd
      - @submission.authors.each do |author|
        = author.full_name
        %br
    %dt Recenzenci
    %dd
      - @submission.last_revision.reviews.each do |review|
        = review.reviewer + " - " + review.status
        %br
%h3
  Dziękujemy!  Twoje zgłoszenie zostało wysłane do redakcji Rocznika Kognitywistycznego.

app/views/public_submissions/new.html.haml
= render partial: "timeline"
.scroll-panel-body
  = render partial: "form"

app/views/public_submissions/submission_cancelled.html.haml
.scroll-panel-header
  %h3.scroll-panel-title Anulowano
.scroll-panel-body
  %h4 Twoje zgłoszenie zostało usunięte